spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/myfirstschema
    username: root
    password: GOlden
  driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always